routes/web.php
<?php

use App\Models\Tag;
use App\Models\Site;
use App\Models\User;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TagController;
use App\Http\Controllers\SiteController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\FrontendController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('index');

Route::get('/product/{product}', [FrontendController::class, 'product'])->name('product.detail');

Route::get('/category/{category}', [FrontendController::class, 'category'])->name('product.category');

Route::get('/tag/{tag}', [FrontendController::class, 'tag'])->name('product.tag');

Route::middleware(['auth'])->group(function () {
    Route::view('dashboard', 'dashboard', [
        'user' => User::count(),
        'category' => Category::count(),
        'tag' => Tag::count(),
        'product' => Product::count(),
        'sites' => Site::all(),
        'latest_product' => Product::take(5)->latest()->get()
    ])->name('dashboard');
    Route::middleware(['role:admin'])->group(function () {
        Route::get('site/{site}', [SiteController::class, 'edit'])->name('site.edit');
        Route::patch('site/{site}', [SiteController::class, 'update'])->name('site.update');

        Route::resource('users', UserController::class);
        Route::resource('categories', CategoryController::class);
        Route::resource('tags', TagController::class);
    });
    Route::middleware(['role:admin|user'])->group(function () {
        Route::resource('products', ProductController::class);
    });
});

Route::get('locale/{locale}', function ($locale) {
     session()->put('locale', $locale);
     return redirect()->back();
})->name('locale');

require __DIR__.'/auth.php';

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function scopeName($query, $search)
    {
        return $query->where('name', 'like', '%'.$search.'%');
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Tag\StoreRequest;
use App\Http\Requests\Tag\UpdateRequest;
use App\Models\Tag;
use Illuminate\Http\Request;

class TagController extends Controller
{
    public function index(Request $request)
    {
        $tags = $request->get('search') ? Tag::latest()->name($request->get('search'))->paginate(10) : Tag::latest()->paginate(10);
        return view('backend.tags.index', ['tags' => $tags]);
    }

    public function create()
    {
        return view('backend.tags.create');
    }

    public function store(StoreRequest $request)
    {
        Tag::create($request->all());
        return redirect()->route('tags.index')->with('success', trans('alert.created'));
    }

    public function edit(Tag $tag)
    {
        return view('backend.tags.edit', ['tag' => $tag]);
    }

    public function update(UpdateRequest $request, Tag $tag)
    {
        Tag::where('id', $tag->id)->update($request->only(['name']));
        return redirect()->route('tags.index')->with('success', trans('alert.updated'));
    }

    public function destroy(Tag $tag)
    {
        $tag->delete();
        return back()->with('success', trans('alert.deleted'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/backend/tags/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('messages.create', ['name' => trans('messages.tag')]) }}
        </h2>
    </x-slot>

    <x-slot name="back"> {{ route('tags.index') }} </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />
                    <form method="POST" action="{{ route('tags.store') }}">
                        @csrf
                        <div class="mt-4 mb-6">
                            <x-label for="name" :value="__('form.name')" />
                            <x-input id="name" class="block mt-1 w-full" type="text" name="name" :value="old('name')" required autofocus />
                        </div>
                        <div class="flex items-center justify-center mt-4 mb-6">
                            <x-button class="w-full my-5 h-12 text-base">
                                {{ __('form.save') }}
                            </x-button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/backend/tags/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('messages.edit', ['name' => trans('messages.tag')]) }}
        </h2>
    </x-slot>

    <x-slot name="back"> {{ route('tags.index') }} </x-slot>
    
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />
                    <form method="POST" action="{{ route('tags.update', $tag->id) }}">
                        @method('PATCH')
                        @csrf
                        <div class="mt-4 mb-6">
                            <x-label for="name" :value="__('form.name')" />
                            <x-input id="name" class="block mt-1 w-full" type="text" name="name" value="{{ $tag->name }}" required autofocus />
                        </div>
                        <div class="flex items-center justify-center mt-4 mb-6">
                            <x-button class="w-full my-5 h-12 text-base">
                                {{ __('form.save') }}
                            </x-button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/backend/tags/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('menu.tag') }}
        </h2>
    </x-slot>

    @permission('tags-create')
    <x-slot name="create"> {{ route('tags.create') }} </x-slot>
    @endpermission

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="flex items-center">
                        <div class="w-full mx-auto rounded-xlp-10">
                            <div class="relative mt-5 mb-10">
                                <form>
                                    <x-search-input type="text" id="search" name="search" placeholder="{{ trans('table.search') }}" />
                                    <x-search-button>
                                        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                                        </svg>
                                    </x-search-button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="flex items-center">
                        <table class="border-collapse w-full">
                            <thead>
                                <tr>
                                    <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell">#</th>
                                    <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell">{{ __('table.name') }}</th>
                                    <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell">{{ __('table.actions') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($tags as $item)
                                <tr class="bg-white lg:hover:bg-gray-100 flex lg:table-row flex-row lg:flex-row flex-wrap lg:flex-no-wrap mb-10 lg:mb-0">
                                    <td class="w-full lg:w-1/12 p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
                                        <span class="lg:hidden absolute top-0 left-0 bg-blue-200 px-2 py-1 text-xs font-bold uppercase"> # </span>
                                        {{ ++$loop->index }}
                                    </td>
                                    <td class="w-full lg:w-4/12 p-3 text-gray-800 text-left xs:text-center border border-b block lg:table-cell relative lg:static">
                                        <span class="lg:hidden absolute top-0 left-0 bg-blue-200 px-2 py-1 text-xs font-bold uppercase">{{ __('table.name') }}</span>
                                        {{ $item->name }}
                                    </td>
                                    <td class="w-full lg:w-1/12 p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
                                        @include('includes.action', ['name' => 'tags', 'id' => $item->id])
                                    </td>
                                </tr>
                                @empty
                                <tr class="bg-white lg:hover:bg-gray-100 flex lg:table-row flex-row lg:flex-row flex-wrap lg:flex-no-wrap mb-10 lg:mb-0">
                                    <td colspan="4" class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
                                        {{ __('table.no_data') }}
                                    </td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                    <div class="items-center mt-5">
                        <div class="row m-auto">
                            {{ $tags->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

@if (session('success'))
<script>
    const swal = Swal.mixin({
        customClass: {
            title: 'sweet-title',
        }
    });
    swal.fire({
      icon: 'success',
      title: @json(session('success')),
      showConfirmButton: false,
      timer: 1500
    })
</script>
@endif