routes/web.php
<?php

use App\Models\Tag;
use App\Models\Site;
use App\Models\User;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TagController;
use App\Http\Controllers\SiteController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\FrontendController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('index');

Route::get('/product/{product}', [FrontendController::class, 'product'])->name('product.detail');

Route::get('/category/{category}', [FrontendController::class, 'category'])->name('product.category');

Route::get('/tag/{tag}', [FrontendController::class, 'tag'])->name('product.tag');

Route::middleware(['auth'])->group(function () {
    Route::view('dashboard', 'dashboard', [
        'user' => User::count(),
        'category' => Category::count(),
        'tag' => Tag::count(),
        'product' => Product::count(),
        'sites' => Site::all(),
        'latest_product' => Product::take(5)->latest()->get()
    ])->name('dashboard');
    Route::middleware(['role:admin'])->group(function () {
        Route::get('site/{site}', [SiteController::class, 'edit'])->name('site.edit');
        Route::patch('site/{site}', [SiteController::class, 'update'])->name('site.update');

        Route::resource('users', UserController::class);
        Route::resource('categories', CategoryController::class);
        Route::resource('tags', TagController::class);
    });
    Route::middleware(['role:admin|user'])->group(function () {
        Route::resource('products', ProductController::class);
    });
});

Route::get('locale/{locale}', function ($locale) {
     session()->put('locale', $locale);
     return redirect()->back();
})->name('locale');

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'username',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Role;
use Illuminate\Support\Facades\Hash;
use App\Http\Requests\User\StoreRequest;
use App\Http\Requests\User\UpdateRequest;

class UserController extends Controller
{
    public function index()
    {
        return view('backend.users.index', ['users' =>  User::latest()->paginate(10)]);
    }

    public function create()
    {
        return view('backend.users.create')->with('roles', Role::all());
    }

    public function store(StoreRequest $request)
    {
        $user = User::create([
            'name' => $request->name,
            'username' => $request->username,
            'password' => Hash::make($request->password),
        ]);

        $user->attachRoles($request->roles);

        return redirect()->route('users.index')->with('success', trans('alert.created'));
    }

    public function show(User $user)
    {
        return view('backend.users.show', ['user' => $user]);
    }

    public function edit(User $user)
    {
        return view('backend.users.edit', ['user' => $user])->with('roles', Role::all());
    }

    public function update(UpdateRequest $request, User $user)
    {
        User::where('id', $user->id)->update([
            'name' => $request->name,
            'username' => $request->username,
            'password' => Hash::make($request->password),
        ]);

        $user->syncRoles($request->roles);

        return redirect()->route('users.index')->with('success', 'Updated!');
    }

    public function destroy(User $user)
    {
       $user->delete();
       return back()->with('success', trans('alert.deleted'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/backend/users/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('messages.create', ['name' => trans('messages.user')]) }}
        </h2>
    </x-slot>

    <x-slot name="back"> {{ route('users.index') }} </x-slot>
    
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />
                    <form method="POST" action="{{ route('users.store') }}">
                        @csrf
                        <div class="mt-4 mb-6">
                            <x-label for="name" :value="__('form.name')" />
                            <x-input id="name" class="block mt-1 w-full" type="text" name="name" :value="old('name')" required autofocus />
                        </div>
                        <div class="mt-4 mb-6">
                            <x-label for="username" :value="__('form.username')" />
                            <x-input id="username" class="block mt-1 w-full" type="text" name="username" :value="old('username')" required autofocus />
                        </div>
                        <div class="mt-4 mb-6">
                            <x-label for="password" :value="__('form.password')" />
                            <x-input id="password" class="block mt-1 w-full" type="password" name="password" required autocomplete="current-password" />
                        </div>
                        <div class="mt-4 mb-6">
                            <x-label for="password_confirmation" :value="__('form.password_confirmation')" />
                            <x-input id="password_confirmation" class="block mt-1 w-full" type="password" name="password_confirmation" required />
                        </div>
                        <div class="mt-4 mb-6">
                            <x-label for="roles" :value="__('form.roles')" />
                            <x-select name="roles[]" id="roles" class="block mt-1 w-full" multiple>
                                @foreach ($roles as $role)
                                <option value="{{ $role->id }}">{{ $role->name }}</option>
                                @endforeach
                            </x-select>
                        </div>

                        <div class="flex items-center justify-center mt-4 mb-6">
                            <x-button class="w-full my-5 h-12 text-base">
                                {{ __('form.save') }}
                            </x-button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/backend/users/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('messages.edit', ['name' => trans('messages.user')]) }}
        </h2>
    </x-slot>

    <x-slot name="back"> {{ route('users.index') }} </x-slot>
    
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />
                    <form method="POST" action="{{ route('users.update', $user->id) }}">
                        @csrf
                        @method('PATCH')
                        <div class="mt-4 mb-6">
                            <x-label for="name" :value="__('form.name')" />
                            <x-input id="name" class="block mt-1 w-full" type="text" name="name" value="{{ $user->name }}" required autofocus />
                        </div>
                        <div class="mt-4 mb-6">
                            <x-label for="username" :value="__('form.username')" />
                            <x-input id="username" class="block mt-1 w-full" type="text" name="username" value="{{ $user->username }}" required autofocus />
                        </div>
                        <div class="mt-4 mb-6">
                            <x-label for="password" :value="__('form.password')" />
                            <x-input id="password" class="block mt-1 w-full" type="password" name="password" required autocomplete="current-password" />
                        </div>
                        <div class="mt-4 mb-6">
                            <x-label for="password_confirmation" :value="__('form.password_confirmation')" />
                            <x-input id="password_confirmation" class="block mt-1 w-full" type="password" name="password_confirmation" required />
                        </div>
                        <div class="mt-4 mb-6">
                            <x-label for="roles" :value="__('form.roles')" />
                            <x-select name="roles[]" id="roles" class="block mt-1 w-full" multiple>
                                @foreach ($roles as $role)
                                    <option value="{{ $role->id }}" {{ $user->roles->pluck('id')->contains($role->id) ? 'selected' : '' }}>{{ $role->name }}</option>
                                @endforeach
                            </x-select>
                        </div>
                        <div class="flex items-center justify-center mt-4 mb-6">
                            <x-button class="w-full my-5 h-12 text-base">
                                {{ __('form.save') }}
                            </x-button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/backend/users/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('menu.user') }}
        </h2>
    </x-slot>

    @permission('users-create')
    <x-slot name="create"> {{ route('users.create') }} </x-slot>
    @endpermission

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <table class="border-collapse w-full">
                        <thead>
                            <tr>
                                <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell"> # </th>
                                <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell"> {{ __('table.name') }} </th>
                                <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell"> {{ __('table.username') }} </th>
                                <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell"> {{ __('table.actions') }} </th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($users as $item)
                            <tr class="bg-white lg:hover:bg-gray-100 flex lg:table-row flex-row lg:flex-row flex-wrap lg:flex-no-wrap mb-10 lg:mb-0">
                                <td class="w-full lg:w-1/12 p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
                                    <span class="lg:hidden absolute top-0 left-0 bg-blue-200 px-2 py-1 text-xs font-bold uppercase"> # </span>
                                    {{ ++$loop->index }}
                                </td>
                                <td class="w-full lg:w-1/2 p-3 text-gray-800 text-left xs:text-center border border-b block lg:table-cell relative lg:static">
                                    <span class="lg:hidden absolute top-0 left-0 bg-blue-200 px-2 py-1 text-xs font-bold uppercase">{{ __('table.name') }}</span>
                                    {{ $item->name }}
                                </td>
                                <td class="w-full lg:w-1/4 p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
                                    <span class="lg:hidden absolute top-0 left-0 bg-blue-200 px-2 py-1 text-xs font-bold uppercase">{{ __('table.username') }}</span>
                                    {{ $item->username }}
                                </td>
                                <td class="w-full lg:w-2/12 p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
                                    @include('includes.action', ['name' => 'users', 'id' => $item->id])
                                </td>
                            </tr>
                            @empty
                            <tr class="bg-white lg:hover:bg-gray-100 flex lg:table-row flex-row lg:flex-row flex-wrap lg:flex-no-wrap mb-10 lg:mb-0">
                                <td colspan="4" class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
                                    {{ __('table.no_data') }}...
                                </td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                    <div class="items-center mt-5">
                        <div class="row m-auto">
                            {{ $users->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

@if (session('success'))
<script>
    const swal = Swal.mixin({
        customClass: {
            title: 'sweet-title',
        }
    });
    swal.fire({
      icon: 'success',
      title: @json(session('success')),
      showConfirmButton: false,
      timer: 1500
    })
</script>
@endif

resources/views/backend/users/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
          {{ __('messages.show', ['name' => trans('messages.user')]) }}
        </h2>
    </x-slot>

    <x-slot name="back"> {{ route('users.index') }} </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="container px-5 py-5 mx-auto flex flex-col">
                        <div class="lg:w-full mx-auto">
                          <div class="flex flex-col sm:flex-row mt-10">
                            <div class="sm:w-1/3 text-center sm:pr-8 sm:py-8">
                              <div class="w-20 h-20 rounded-full inline-flex items-center justify-center bg-gray-200 text-gray-400">
                                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
                                  <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                                  <circle cx="12" cy="7" r="4"></circle>
                                </svg>
                              </div>
                              <div class="flex flex-col items-center text-center justify-center">
                                <h2 class="font-medium title-font mt-4 mb-6 text-gray-900 text-lg"> {{ $user->name }}</h2>
                                <div class="w-12 h-1 bg-blue-500 rounded mt-2 mb-4"></div>
                                <h2 class="text-gray-900 font-medium title-font tracking-wider text-sm m-2"> {{ __('form.username') }}</h2>
                                <p class="text-gray-500 mt-2">{{ $user->username }}</p>
                              </div>
                            </div>
                            <div class="sm:w-2/3 sm:pl-8 sm:py-8 sm:border-l border-gray-200 sm:border-t-0 border-t mt-4 mb-6 pt-4 sm:mt-0 text-center sm:text-left">
                                <div class="container px-5 py-5 mx-auto">
                                    <div class="flex flex-wrap -m-2">
                                        @foreach ($user->roles as $role)
                                        <div class="p-2 lg:w-1/2 md:w-1/2 w-full">
                                            <div class="h-full flex items-center border-gray-200 border p-4 rounded-lg">
                                              <div class="flex-grow">
                                                <h2 class="text-gray-900 title-font font-medium mb-2"> Role : {{ $role->name }} </h2>
                                                @foreach ($role->permissions as $permission)
                                                <p class="text-gray-500">
                                                    <span class="bg-blue-100 text-blue-500 w-4 h-4 mr-2 rounded-full inline-flex items-center justify-center m-2">
                                                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="3" class="w-3 h-3" viewBox="0 0 24 24">
                                                        <path d="M20 6L9 17l-5-5"></path>
                                                        </svg>
                                                    </span>
                                                    {{ $permission->name }}
                                                </p>
                                                @endforeach
                                              </div>
                                            </div>
                                          </div>
                                        @endforeach
                                    </div>
                                </div>
                            </div>
                          </div>
                        </div>
                      </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>