routes/web.php
<?php

use App\Models\Tag;
use App\Models\Site;
use App\Models\User;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TagController;
use App\Http\Controllers\SiteController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\FrontendController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('index');

Route::get('/product/{product}', [FrontendController::class, 'product'])->name('product.detail');

Route::get('/category/{category}', [FrontendController::class, 'category'])->name('product.category');

Route::get('/tag/{tag}', [FrontendController::class, 'tag'])->name('product.tag');

Route::middleware(['auth'])->group(function () {
    Route::view('dashboard', 'dashboard', [
        'user' => User::count(),
        'category' => Category::count(),
        'tag' => Tag::count(),
        'product' => Product::count(),
        'sites' => Site::all(),
        'latest_product' => Product::take(5)->latest()->get()
    ])->name('dashboard');
    Route::middleware(['role:admin'])->group(function () {
        Route::get('site/{site}', [SiteController::class, 'edit'])->name('site.edit');
        Route::patch('site/{site}', [SiteController::class, 'update'])->name('site.update');

        Route::resource('users', UserController::class);
        Route::resource('categories', CategoryController::class);
        Route::resource('tags', TagController::class);
    });
    Route::middleware(['role:admin|user'])->group(function () {
        Route::resource('products', ProductController::class);
    });
});

Route::get('locale/{locale}', function ($locale) {
     session()->put('locale', $locale);
     return redirect()->back();
})->name('locale');

require __DIR__.'/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function child()
    {
        return $this->hasMany(Category::class, 'parent_id');
    }

    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_id');
    }

    public function scopeName($query, $search)
    {
        return $query->where('name', 'like', '%'.$search.'%');
    }

    public function scopeActive($query)
    {
        return $query->where('status', 1);
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Category\StoreRequest;
use App\Http\Requests\Category\UpdateRequest;
use Illuminate\Http\Request;
use App\Models\Category;

class CategoryController extends Controller
{
    public function index(Request $request)
    {
        $categories = $request->get('search') ? Category::latest()->name($request->get('search'))->paginate(10) : Category::latest()->paginate(10);
        return view('backend.categories.index', ['categories' => $categories]);
    }

    public function create()
    {
        return view('backend.categories.create', ['parents' => Category::all()]);
    }

    public function store(StoreRequest $request)
    {
        Category::create($request->all());
        return redirect()->route('categories.index')->with('success', trans('alert.created'));
    }

    public function show(Category $category)
    {
        return view('backend.categories.show', ['category' => $category]);
    }

    public function edit(Category $category)
    {
        return view('backend.categories.edit', ['category' => $category])->with('parents', Category::latest()->get());
    }

    public function update(UpdateRequest $request, Category $category)
    {
        Category::where('id', $category->id)->update($request->only(['name', 'status', 'parent_id']));
        return redirect()->route('categories.index')->with('success', trans('alert.updated'));
    }

    public function destroy(Category $category)
    {
        $category->delete();
        return back()->with('success', trans('alert.deleted'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/backend/categories/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('messages.create', ['name' => trans('messages.category')]) }}
        </h2>
    </x-slot>

    <x-slot name="back"> {{ route('categories.index') }} </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />
                    <form method="POST" action="{{ route('categories.store') }}">
                        @csrf
                        <div class="mt-4 mb-6">
                            <x-label for="name" :value="__('form.name')" />
                            <x-input id="name" class="block mt-1 w-full" type="text" name="name" :value="old('name')" required autofocus />
                        </div>
                        <div class="mt-4 mb-6">
                            <x-label for="name" :value="__('form.status')" />
                            <x-select name="status" class="block mt-1 w-full">
                                <option value="1" selected> {{ __('form.status_detail.active') }} </option>
                                <option value="0"> {{ __('form.status_detail.in_active') }} </option>
                            </x-select>
                        </div>
                        <div class="mt-4 mb-6">
                            <x-label for="parent" :value="__('form.parent')" />
                            <x-select name="parent_id" id="parent_id" class="block mt-1 w-full">
                                <option value="" selected disabled> {{ __('form.select_parent') }} </option>
                                <option value="0">  {{ __('form.no_parent') }} </option>
                                @foreach ($parents as $p)
                                    @if ($p->child->count() && $p->parent_id == 0)
                                        <option value="{{ $p->id }}"> {{ $p->name }} </option>
                                        @foreach ($p->child as $item)
                                            <option value="{{ $item->id }}">  ↪  {{ $item->name }} </option>
                                            @includeWhen($item->child->count(), 'includes.category', ['item' => $item, 'count' => $item->child->count(), 'category_parent' => null, 'category_id' => null])
                                        @endforeach
                                    @endif
                                    @if($p->parent_id == 0 && $p->child->count() == 0)
                                        <option value="{{ $p->id }}"> {{ $p->name }} </option>
                                    @endif
                                @endforeach
                            </x-select>
                        </div>
                        <div class="flex items-center justify-center mt-4 mb-6">
                            <x-button class="w-full my-5 h-12 text-base">
                                {{ __('form.save') }}
                            </x-button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/backend/categories/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('messages.edit', ['name' => trans('messages.category')]) }}
        </h2>
    </x-slot>

    <x-slot name="back"> {{ route('categories.index') }} </x-slot>
    
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />
                    <form method="POST" action="{{ route('categories.update', $category->id) }}">
                        @method('PATCH')
                        @csrf
                        <div class="mt-4 mb-6">
                            <x-label for="name" :value="__('form.name')" />
                            <x-input id="name" class="block mt-1 w-full" type="text" name="name" value="{{ $category->name }}" required autofocus />
                        </div>
                        <div class="mt-4 mb-6">
                            <x-label for="name" :value="__('form.status')" />
                            <x-select name="status" class="block mt-1 w-full">
                                <option value="1" {{ $category->status == 1 ? 'selected' : '' }}> {{ __('form.status_detail.active') }} </option>
                                <option value="0" {{ $category->status == 0 ? 'selected' : '' }}> {{ __('form.status_detail.in_active') }} </option>
                            </x-select>
                        </div>
                        <div class="mt-4 mb-6">
                            <x-label for="parent" :value="__('form.parent')" />
                            <x-select name="parent_id" id="parent_id" class="block mt-1 w-full">
                                <option value="" selected disabled> {{ __('form.select_parent') }} </option>
                                <option value="0" {{ $category->parent_id == 0 ? 'selected' : '' }}>  {{ __('form.no_parent') }} </option>
                                @foreach ($parents as $p)
                                    @if ($p->child->count() && $p->parent_id == 0)
                                        <option value="{{ $p->id }}" {{ $category->parent_id == $p->id ? 'selected' : '' }}  {{ $p->id == $category->id ? 'disabled' : '' }}> {{ $p->name }} </option>
                                        @foreach ($p->child as $item)
                                            <option value="{{ $item->id }}" {{ $category->parent_id == $item->id ? 'selected' : '' }}  {{ $item->id == $category->id ? 'disabled' : '' }}>  ↪ {{ $item->name }} </option>
                                            @includeWhen($item->child->count(), 'includes.category', ['item' => $item, 'count' => $item->child->count(), 'category_parent' => $category->parent_id, 'category_id' => $category->id])
                                        @endforeach
                                    @endif
                                    @if($p->parent_id == 0 && $p->child->count() == 0)
                                        <option value="{{ $p->id }}"> {{ $p->name }} </option>
                                    @endif
                                @endforeach
                            </x-select>
                        </div>
                        <div class="flex items-center justify-center mt-4 mb-6">
                            <x-button class="w-full my-5 h-12 text-base">
                                {{ __('form.save') }}
                            </x-button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/backend/categories/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('menu.category') }}
        </h2>
    </x-slot>

    @permission('categories-create')
    <x-slot name="create"> {{ route('categories.create') }} </x-slot>
    @endpermission

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="flex items-center">
                        <div class="w-full mx-auto rounded-xlp-10">
                            <div class="relative mt-5 mb-10">
                                <form>
                                    <x-search-input type="text" id="search" name="search" placeholder="{{ trans('table.search') }}" />
                                    <x-search-button>
                                        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                                        </svg>
                                    </x-search-button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="flex items-center">
                        <table class="border-collapse w-full">
                            <thead>
                                <tr>
                                    <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell">#</th>
                                    <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell">{{ __('table.name') }}</th>
                                    <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell">{{ __('table.status') }}</th>
                                    <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell">{{ __('table.actions') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($categories as $item)
                                <tr class="bg-white lg:hover:bg-gray-100 flex lg:table-row flex-row lg:flex-row flex-wrap lg:flex-no-wrap mb-10 lg:mb-0">
                                    <td class="w-full lg:w-1/12 p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
                                        <span class="lg:hidden absolute top-0 left-0 bg-blue-200 px-2 py-1 text-xs font-bold uppercase"> # </span>
                                        {{ ++$loop->index }}
                                    </td>
                                    <td class="w-full lg:w-4/12 p-3 text-gray-800 text-left xs:text-center border border-b block lg:table-cell relative lg:static">
                                        <span class="lg:hidden absolute top-0 left-0 bg-blue-200 px-2 py-1 text-xs font-bold uppercase">{{ __('table.name') }}</span>
                                        {{ $item->name }}
                                        @if ($item->child->count())
                                        <span class="text-blue-800">  ( {{ $item->child->count() }} ) </span>
                                        @endif
                                    </td>
                                    <td class="w-full lg:w-1/12 p-3 text-gray-800 text-center xs:text-center border border-b block lg:table-cell relative lg:static">
                                        <span class="lg:hidden absolute top-0 left-0 bg-blue-200 px-2 py-1 text-xs font-bold uppercase">{{ __('table.status') }}</span>
                                        @switch($item->status)
                                            @case(0) <span class="bg-red-200 text-gray-600 py-1 px-3 rounded-full text-xs">{{ __('form.status_detail.in_active') }}</span>  @break
                                            @case(1) <span class="bg-green-200 text-gray-600 py-1 px-3 rounded-full text-xs">{{ __('form.status_detail.active') }}</span> @break
                                            @default
                                        @endswitch
                                    </td>
                                    <td class="w-full lg:w-1/12 p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
                                        @include('includes.action', ['name' => 'categories', 'id' => $item->id])
                                    </td>
                                </tr>
                                @empty
                                <tr class="bg-white lg:hover:bg-gray-100 flex lg:table-row flex-row lg:flex-row flex-wrap lg:flex-no-wrap mb-10 lg:mb-0">
                                    <td colspan="4" class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
                                        {{ __('table.no_data') }}
                                    </td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                    <div class="items-center mt-5">
                        <div class="row m-auto">
                            {{ $categories->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

@if (session('success'))
<script>
    const swal = Swal.mixin({
        customClass: {
            title: 'sweet-title',
        }
    });
    swal.fire({
      icon: 'success',
      title: @json(session('success')),
      showConfirmButton: false,
      timer: 1500
    })
</script>
@endif

resources/views/backend/categories/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('messages.show', ['name' => trans('messages.category')]) }}
        </h2>
    </x-slot>

    <x-slot name="back"> {{ route('categories.index') }} </x-slot>
    
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="container px-5 py-5 mx-auto flex flex-col">
                        <div class="lg:w-full mx-auto">
                          <div class="flex flex-col sm:flex-row mt-10">
                            <div class="sm:w-1/3 text-center sm:pr-8 sm:py-8">
                              <div class="w-20 h-20 rounded-full inline-flex items-center justify-center bg-gray-200 text-gray-400">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                                  </svg>
                              </div>
                              <div class="flex flex-col items-center text-center justify-center">
                                <h2 class="font-medium title-font mt-4 mb-6 text-gray-900 text-lg"> {{ $category->name }}</h2>
                                <div class="w-12 h-1 bg-blue-500 rounded mt-2 mb-4"></div>
                                <h2 class="text-gray-900 font-medium title-font tracking-wider text-sm m-2"> {{ __('table.parent') }}</h2>
                                <p class="text-gray-500 mt-2">{{ $category->parent->name ?? null }}</p>
                              </div>
                            </div>
                            <div class="sm:w-2/3 sm:pl-8 sm:py-8 sm:border-l border-gray-200 sm:border-t-0 border-t mt-4 mb-6 pt-4 sm:mt-0 text-center sm:text-left">
                                <div class="container px-5 py-5 mx-auto">
                                    <div class="flex flex-wrap">
                                        @if ($category->child->count())
                                            @foreach ($category->child as $item)
                                            <div class="p-2 lg:w-1/2 md:w-1/2 w-full">
                                                <div class="h-full flex items-center border-gray-200 border p-4 rounded-lg">
                                                <div class="flex-grow">
                                                    <h2 class="text-gray-900 title-font font-medium mb-2"> {{ __('table.child') }} : {{ $item->name }} </h2>
                                                </div>
                                                </div>
                                            </div>
                                            @endforeach
                                        @else
                                        <p class="text-gray-500 mt-2">{{ __('table.no_child') }}</p>
                                        @endif
                                    </div>
                                </div>
                            </div>
                          </div>
                        </div>
                      </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>